# Generated by Django 5.0.6 on 2024-06-10 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=40)),
                ('requested_for', models.JSONField(verbose_name='Requested For')),
                ('time_stamp', models.DateTimeField(auto_now_add=True, verbose_name='Time Stamp')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=10)),
                ('slug', models.CharField(max_length=30)),
                ('data', models.JSONField(verbose_name='Json Data')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.job')),
            ],
        ),
    ]
